<ProgressViewWindow>:
    name: "progress_view"

    FloatLayout:
        # rice the layout
        canvas.before:
            Color:
                rgba: app.bg_color
            Rectangle:
                pos: self.pos
                size: self.size

        # ------------exit btn--------------
        AnchorLayout:
            anchor_x: "center"
            anchor_y: "top"

            # exit btn
            Button:
                text: "<- Discard & Back"

                size_hint: None, 0.05
                size: 360, 40

                halign: "left"
                valign: "middle"
                text_size: self.width, None
                padding: 10, 0

                color: app.text_color
                background_color: app.back_btn_color
                background_normal: ''
                canvas.before:
                    Color:
                        rgba: app.outline_color   
                    Line:
                        width: 2
                        rectangle: (self.x, self.y, self.width, self.height)
                on_release:
                    app.root.current = "main"
                    root.manager.transition.direction = "right"
                    app.root.get_screen('main').add_the_info(True)

        # ------------progress rectangle------------
        ScrollView:
            id: table
            size_hint: 0.9, None  # width = 90% of screen, height fixed
            height: root.height * 0.5
            pos_hint: {"center_x": 0.5, "top": 0.9}  # below header, center horizontally

            # outline where the progress will be
            canvas.before:
                Color:
                    rgba: app.outline_color
                Line:
                    width: 1.5
                    rectangle: (self.x, self.y, self.width, self.height)

            GridLayout:
                id: table_grid
                cols: 1  # Set dynamically in Python
                size_hint: None, None
                width: self.minimum_width
                height: self.minimum_height
        
        FloatLayout:

            Label:
                text:''
                font_name: "FontAwesome"
                font_size: '32sp'
                color: app.text_color
                pos_hint: {"center_x":0.15, "center_y":0.3}

            Label:
                id: streak
                text: "Streak: "
                font_size: '32sp'
                color: app.text_color
                pos_hint: {"center_x":0.55, "center_y":0.295}

